### PR TITLE
fist commit

### PR DESCRIPTION
**Pull request by reliableJARED**
OK so this took a bit to figure out.  First I created a fork using this guide: https://help.github.com/articles/fork-a-repo/
 
I then had to sync that fork to my local machine using this guide: https://help.github.com/articles/syncing-a-fork/

THen I made some local changes to the files.  THen do a cd to the local repository directory, for me its: /home/jared/PythonWork/git/SQLite_Test
in the terminal once your at that folder do:
git init
git add .
git commit -m "commit comment text here"
git push -u origin master

### CODE REVIEW

**Comment by reliableJARED** [comment]
I used:http://guides.railsgirls.com/github/
to figure out the push

**Comment by crbeaver** [comment]
i used rails girls docs too. Good stuff.

**Comment by reliableJARED** [comment]
yeah, it was really helpful.  messed me up because when you make changes
you first have to put them in the 'staging area' with git commit, then you
can push.  If you make changes and just try to push wont work.

On 17 August 2015 at 14:01, crbeaver <notifications@github.com> wrote:

> i used rails girls docs too. Good stuff.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crbeaver/SQLite_Test/pull/1#issuecomment-131910563>.
>



-- 

- Jared Nugent

**Comment by reliableJARED** [comment]
sweet


On 17 August 2015 at 14:04, crbeaver <notifications@github.com> wrote:

> Merged #1 <https://github.com/crbeaver/SQLite_Test/pull/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crbeaver/SQLite_Test/pull/1#event-384511961>.
>



-- 

- Jared Nugent

**Comment by crbeaver** [comment]
Yeah, its a bit confusing. Empty repos have that info laid out directly on the start page when asking if you want to add a readme file.

Either way, we're on the path to success. clone the upload_test repo when you get home and run the main_workflow file to see if the database functions work. Let me know.

**Pull request merged**
